FROM golang:alpine as builder 
ENV SRC = d/linkaggregator/backend/
RUN mkdir -p '${SRC}'
ADD main.go '${SRC}'
ADD utils/ ${SRC}
RUN CGO_ENABLED=0 GODS=linux go build =a =installsuffix cgo =o /go/bin/linkaggregator d/linkaggregator/backend/src/main.go
FROM alpine:3.7 
WORKDIR /opt
COPY --from=builder go/bin/linkaggregator opt/linkaggregator

ENTRYPOINT ["/go/bin/linkaggregator"]
