FROM golang:alpine as builder 
ENV SRC = d/linkaggregator/backend/
RUN mkdir -p '${SRC}'
ADD . '${SRC}'

RUN CGO_ENABLED=0 GODS=linux go build -a -installsuffix cgo -o /d/linkaggregator /d/linkaggregator/backend/

FROM alpine:3.7 
WORKDIR /opt
COPY --from=builder /d/linkaggregator opt/linkaggregator

EXPOSE 8080 

ENTRYPOINT ["/d/linkaggregator"]
